from pathlib import Path
p=Path(__file__).parent;s=(p/'stellar_search.cpp').read_text()
s=s.replace('int EU[M],EV[M],EI[N][N],tid[N][N][N];','int EU[M],EV[M],EI[N][N],tid[N][N][N]; bool TARGET[M]{};')
s=s.replace('int triangles=0,overlap=0;','int triangles=0,overlap=0,missing=0;')
s=s.replace('triangles/=3;}','triangles/=3;missing=0;for(int ee=0;ee<M;ee++)if(TARGET[ee]&&!t[0].inc[ee]&&!t[1].inc[ee])missing++;}')
s=s.replace('void apply(const Flip&r){auto d=delta(r);','void apply(const Flip&r){auto d=delta(r);missing+=(TARGET[r.old]&&!t[1-r.layer].inc[r.old])-(TARGET[r.neu]&&!t[1-r.layer].inc[r.neu]);')
s=s.replace('void undo(const Flip&r){t[r.layer].undo(r);','void undo(const Flip&r){missing-=(TARGET[r.old]&&!t[1-r.layer].inc[r.old])-(TARGET[r.neu]&&!t[1-r.layer].inc[r.neu]);t[r.layer].undo(r);')
s=s.replace('s.overlap!=overlap)','s.overlap!=overlap||s.missing!=missing)')
s=s.replace('if(argc!=6)','if(argc!=7)').replace('output.json\\n','output.json target.edges\\n')
s=s.replace('State initial;ifstream in(argv[1]);','ifstream targetin(argv[6]);if(!targetin)throw runtime_error("target input");int aa,bb;while(targetin>>aa>>bb){if(aa<0||aa>=N||bb<0||bb>=N||aa==bb)throw runtime_error("target edge");TARGET[EI[aa][bb]]=true;} State initial;ifstream in(argv[1]);')
s=s.replace('if(total<1||','if(total<1||mode=="weighted"||')
s=s.replace('if(make_pair(s.triangles,s.overlap)<make_pair(best.triangles,best.overlap))','if(s.triangles==0||make_tuple(s.missing,s.triangles,s.overlap)<make_tuple(best.missing,best.triangles,best.overlap))')
s=s.replace('double delta=s.triangles-old.triangles+.15*(s.overlap-old.overlap);','double delta=s.missing-old.missing+.05*(s.triangles-old.triangles)+.1*(s.overlap-old.overlap);')
s=s.replace('int oldt=s.triangles,oldo=s.overlap;','int oldt=s.triangles,oldo=s.overlap,oldm=s.missing;')
s=s.replace('double delta=s.triangles-oldt+.15*(s.overlap-oldo);','double delta=s.missing-oldm+.05*(s.triangles-oldt)+.1*(s.overlap-oldo);')
s=s.replace('<<",\\\"faces\\\":["','<<",\\\"missing_target_edges\\\":"<<s.missing<<",\\\"faces\\\":["')
s=s.replace('<<" overlap "<<best.overlap<<" path "','<<" overlap "<<best.overlap<<" missing-target "<<best.missing<<" path "')
s=s.replace('<<" overlap "<<best.overlap<<" attempts "','<<" overlap "<<best.overlap<<" missing-target "<<best.missing<<" attempts "')
s='// Target-guided planar-pair variant; missing target edges are an objective, NOT a partial-layer certificate. Both stored layers always remain full triangulations.\n'+s
s=s.replace('#include <vector>','#include <vector>\n#include <tuple>')
(p/'target_search.cpp').write_text(s)
