#!/usr/bin/env python3
"""Generate complete, runnable requests for each implemented family."""
from pathlib import Path
import json,math,sys
from machine import ROOT,dump
sys.path[:0]=[str(ROOT/'preserved/compound-eye-0.4'),str(ROOT/'preserved/compound-eye-0.4/frontier')]
import compound_lab

def context(model='declared-boundary-model',units='model',kind='setting',value=0.,coordunit='1',source='synthetic'):
    return {'object_id':model+'-example-001','model_id':model,'basis_id':'declared basis','boundary_id':'declared retained sector and channels',
        'coordinate':{'kind':kind,'value':value,'unit':coordunit},'unit_system':units,
        'source':{'kind':source,'id':'explicit example generated by make_examples.py'},'assumptions':['Synthetic or mathematical demonstration; no detector events or nuclear fit.']}
def request(name,ctx,inputs,sets):
    data={'schema':'compound-eye-request-v1','context':ctx,'inputs':{k:{'value':v[0],'unit':v[1]} for k,v in inputs.items()}}
    dump(ROOT/'requests'/(name+'.json'),data);return {'request':'requests/'+name+'.json','sets':['ce.set.'+x+'@1.0.0' for x in sets]}

def main():
    index=ROOT/'requests/project_jobs.json'
    jobs=json.loads(index.read_text()) if index.exists() else {}
    jobs['quantum']=request('quantum',context('closed-hermitian-chain-v1',kind='time',value=2.,coordunit='model_time'),{},['quantum'])
    jobs['electrical']=request('electrical',context('isolated-rc-v1','SI','time',.5,'s'),{'circuit':({'conductance_S':1.,'capacitance_F':2.,'initial_voltage_V':1.},'SI circuit parameters')},['electrical'])
    jobs['geometry']=request('geometry',context('rank-one-geometry-v1',kind='angle',value=math.pi/6,coordunit='rad'),{},['geometry'])
    contracts=json.loads((ROOT/'catalog/models.json').read_text())
    for name in ['quantum','electrical','geometry']:
        path=ROOT/jobs[name]['request'];data=json.loads(path.read_text());model=contracts[data['context']['model_id']]
        data['context']['basis_id']=model['basis_id'];data['context']['boundary_id']=model['boundary_id'];dump(path,data)
    for domain in ['quantum','rc','geometry']:
        p=compound_lab.demo_problem(domain);c=p['context'];ctx=context(c['model_family'],'SI' if c['units_convention']=='SI' else 'model',c['coordinate_kind'],c['coordinate'],'s' if domain=='rc' else 'model_time' if domain=='quantum' else 'rad')
        ctx.update(object_id=c['object_id'],basis_id=c['basis'],boundary_id=c['boundary'])
        sets=['ce.inference.analyze@1.0.0','ce.inference.next@1.0.0','ce.set.prediction_'+domain+'@1.0.0']
        row=request('infer_'+domain,ctx,{'candidate_problem':(p,'declared predictions')},[]);row['sets']=sets;jobs['infer_'+domain]=row
    f={'hamiltonian':([[.6,.3,.12],[.3,1.4,.08],[.12,.08,2.]],'model_energy'),
       'retained_indices':([0],'indices'),'energy':(.9,'model_energy'),'eta':(.07,'model_energy')}
    jobs['operator_boundary']=request('operator_boundary',context(),f,['operator_boundary'])
    continuum={'energies':[round(-1+.01*k,8) for k in range(601)],'eta':0.,'retained_energy':1.1,
        'channels':[{'id':'declared-alpha-alpha-analogue','band_center':2.,'hopping':1.,'coupling':.25}]}
    c={'charges':({'parent':8,'fragments':[4,4],'definition':'Formal additive integer charge; baryon bookkeeping analogy only.','field_map':None},'integer charge'),
       'continuum':(continuum,'model_energy channel parameters'),'experiment':({},'provenance record')}
    jobs['nuclear_boundary']=request('nuclear_boundary',context(),c,['nuclear_boundary'])
    d={'H0':[[0.,1.],[1.,0.]],'linear_terms':[[[1.,0.],[0.,-1.]]],'q':[.2],'classical_stiffness':[[3.]],'state_index':0}
    jobs['deformation']=request('deformation',context('finite-deformation-model'),{'deformation':(d,'model_energy deformation')},['deformation'])
    pts=[[math.cos(2*math.pi*k/64),math.sin(2*math.pi*k/64)] for k in range(64)];pts.append(pts[0])
    jobs['topology']=request('topology',context(),{'closed_curve':(pts,'dimensionless coordinates'),'charges':c['charges']},['topology'])
    cal={'slope':.01,'offset':-.2,'parameter_covariance':[[1e-8,0.],[0.,1e-4]],'adc_sigma':.5}
    jobs['calibration']=request('calibration',context('synthetic-detector-calibration','detector'),{'adc_events':([80.,100.,130.],'ADC counts'),'calibration':(cal,'ADC-to-MeV calibration')},['measurement'])
    base=ROOT/'preserved/compound-eye-0.4'
    graph=json.loads((base/'frontier/examples/earth_moon_c7k4.json').read_text())
    jobs['earth']=request('earth',context('exact-graph','exact'),{'graph':(graph,'graph incidence')},[]);jobs['earth']['sets']=['ce.frontier.graph@1.0.0']
    tower=json.loads((base/'frontier/examples/kt_7_4.json').read_text())
    jobs['arithmetic']=request('arithmetic',context('exact-tower','exact'),{'tower':(tower,'exact tower')},[])
    jobs['arithmetic']['sets']=['ce.frontier.'+x+'@1.0.0' for x in ['admission','cost','transport','forcing','obstruction','cut']]
    sr=json.loads((base/'dag_search/examples/search_baseline.json').read_text())
    jobs['dag']=request('dag',context('exact-tower-search','exact'),{'search_request':(sr,'exact search')},[]);jobs['dag']['sets']=['ce.search.decision_dag@1.0.0']
    dump(ROOT/'requests/project_jobs.json',jobs)
    dump(ROOT/'raw_inputs/nuclear_requirements.json',{'status':'not_obtained','targets':['He-5 alpha+n','Li-5 alpha+proton','Be-8 alpha+alpha'],
        'required':['detector event files','calibration runs and covariance','detector response and efficiency','background and selection procedure','beam/target and channel identification','time and energy conventions'],
        'evaluations_are_not_raw':['AME/NUBASE','TUNL evaluations','ENSDF'],
        'EXFOR_role':'Find experiment provenance and processed numerical observables; inspect each record for actual data level.'})
    print('Wrote',len(jobs),'complete example jobs.')

if __name__=='__main__':main()
