const assert=require('assert'),fs=require('fs'),path=require('path');
const E=require('./mixer_core.js'),P=require('./mixer_plot.js');let tests=[];
function test(name,fn){fn();tests.push(name)}
const near=(a,b)=>assert(Math.abs(a-b)<1e-11,`${a} != ${b}`);
test('Four complete declared presets',()=>E.presets().forEach(E.validate));
test('Linear superposition, not averaging',()=>{let d=E.fromCSV('x [s],a [V],b [V]\n0,1,2\n1,3,4');let s=E.defaults(d);s.channels.import_0.weight=2;s.channels.import_1.weight=-1;assert.deepEqual(E.mix(d,s).combined,[0,2])});
test('Disabled channel contributes nothing',()=>{let d=E.fromCSV('x [s],a [V],b [V]\n0,1,200\n1,3,400');let s=E.defaults(d);s.channels.import_1.enabled=false;assert.deepEqual(E.mix(d,s).combined,[1,3])});
test('Exact outside cancellation for different interiors',()=>{let d=E.presets()[2],s=E.defaults(d);s.channels.inside_a.enabled=s.channels.inside_b.enabled=false;assert(E.mix(d,s).combined.every(v=>v===0))});
test('Opposite phase cancellation',()=>{let d=E.presets()[0];d.traces=d.traces.slice(0,1);let t=E.copy(d.traces[0]);t.id='copy';d.traces.push(t);let s=E.defaults(d);s.channels.copy.phase=180;assert(E.mix(d,s).combined.every(v=>Math.abs(v)<1e-14))});
test('Routes change X/Y while retaining all-channel signal',()=>{let d=E.fromCSV('x [s],a [V],b [V]\n0,1,2\n1,3,4'),s=E.defaults(d);let m=E.mix(d,s);assert.deepEqual(m.X,[1,3]);assert.deepEqual(m.Y,[2,4]);assert.deepEqual(m.combined,[3,7])});
test('Source-unit mismatch refused',()=>{let d=E.presets()[1],s=E.defaults(d);s.normalization='source';assert.throws(()=>E.mix(d,s),/different units/)});
test('RMS transformation recorded and reversible before sum',()=>{let d=E.fromCSV('x [s],a [V]\n0,3\n1,4'),s=E.defaults(d);s.normalization='rms';let m=E.mix(d,s);near(E.rms(m.combined),1);near(m.combined[0]*m.traces[0].transforms.y.scale,3)});
test('Centering removes constants only when requested',()=>{let d=E.fromCSV('x [s],a [V]\n0,3\n1,3'),s=E.defaults(d);assert.deepEqual(E.mix(d,s).combined,[3,3]);s.center=true;assert.deepEqual(E.mix(d,s).combined,[0,0])});
test('Gap propagation is strict; no zero fill',()=>{let d=E.fromCSV('x [s],a [V],b [V]\n0,1,2\n1,,4\n2,5,6');assert.deepEqual(E.mix(d,E.defaults(d)).combined,[3,null,11])});
test('Smoothing cannot bridge a missing sample',()=>assert.deepEqual(E.smooth([0,2,null,100,102],5),[1,1,null,101,101]));
test('Smoothing plus residual reconstructs the original',()=>{let d=E.presets()[0],s=E.defaults(d);s.smoothing=11;let m=E.mix(d,s);m.original.forEach((v,k)=>near(m.combined[k]+m.residual[k],v))});
test('Recipes retain raw data exactly',()=>{let d=E.presets()[0],before=JSON.stringify(d),s=E.defaults(d);s.channels.harmonic_1.phase=90;s.smoothing=9;let r=E.read(JSON.stringify(E.recipe(d,s)));assert.equal(JSON.stringify(d),before);assert.equal(JSON.stringify(r.dataset),before);assert.deepEqual(E.mix(r.dataset,r.settings),E.mix(d,s))});
test('Quoted CSV headers and empty cells parse',()=>{let d=E.fromCSV('"time [s]","a, one [V]"\r\n0,1\r\n1,\r\n');assert.equal(d.traces[0].label,'a, one');assert.equal(d.traces[0].values[1],null)});
test('Misaligned, nonfinite and short imports refused',()=>{for(const csv of ['x,a\n1,2\n0,3','x,a\n0,NaN\n1,3','x,a\n0,1'])assert.throws(()=>E.fromCSV(csv))});
test('SVG cannot execute imported labels or colors',()=>{let d=E.presets()[0];d.title='<script>bad()</script>';let out=P.svg(d,E.defaults(d),E.mix(d,E.defaults(d)));assert(!out.includes('<script>bad'));d.traces[0].color='red" onload="bad()';assert.throws(()=>E.validate(d))});
test('No enabled channels yields a zero trace',()=>{let d=E.presets()[0],s=E.defaults(d);Object.values(s.channels).forEach(c=>c.enabled=false);assert(E.mix(d,s).combined.every(v=>v===0))});
test('Noise is deterministic and is an optional channel',()=>{let a=E.presets()[0],b=E.presets()[0];assert.deepEqual(a.traces.at(-1).values,b.traces.at(-1).values);assert.equal(E.defaults(a).channels.synthetic_noise.enabled,false)});
test('Baseline with another coordinate is refused',()=>{let d=E.presets()[0],s=E.defaults(d),other=E.copy(d);other.x=other.x.map(x=>x+1);assert.throws(()=>E.read(JSON.stringify(E.recipe(d,s,{dataset:other,settings:s}))),/share/)});
test('CSV export reconstructs its display column',()=>{let d=E.presets()[0],s=E.defaults(d),m=E.mix(d,s),rows=E.csv(d,s).trim().split('\n').slice(1);rows.forEach((r,k)=>near(Number(r.split(',')[2]),m.combined[k]))});
test('All presets render trace and shape views',()=>{for(let d of E.presets())for(let view of ['shape','trace']){let s=E.defaults(d);s.view=view;let svg=P.svg(d,s,E.mix(d,s));assert(svg.startsWith('<svg'));assert(!/NaN|Infinity/.test(svg))}});
const out=path.resolve(__dirname,'../../runs/mixer');fs.mkdirSync(out,{recursive:true});
fs.writeFileSync(path.join(out,'verification.json'),JSON.stringify({status:'pass',engine:'1.0.0',tests:tests.length,checks:tests,scope:'Composition mathematics, provenance-preserving transformations, import/export and SVG rendering; not new physical inference.'},null,2));
let d=E.presets()[0],s=E.defaults(d);s.cursor=89;
fs.writeFileSync(path.join(out,'mixer_preview.svg'),P.svg(d,s,E.mix(d,s)));
fs.writeFileSync(path.join(out,'example_recipe.json'),JSON.stringify(E.recipe(d,s),null,2));
console.log(JSON.stringify({status:'pass',tests:tests.length}));
