from pathlib import Path
import json,base64,subprocess,collections,sys
import numpy as np,matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
p=Path(__file__).resolve().parent;sys.path.insert(0,str(p));import machine
reg=machine.Registry(p);eyes=list(reg.eyes.values());status=dict(collections.Counter(x['status'] for x in eyes));r=json.loads((p/'runs/qhe/results.json').read_text());raw=json.loads((p/'research/raw_audit.json').read_text());atomic=json.loads((p/'research/atomic_source_results.json').read_text());pop=json.loads((p/'research/raw_population_replay.json').read_text())
plt.rcParams.update({'font.size':10,'axes.spines.top':False,'axes.spines.right':False})
f,ax=plt.subplots(2,2,figsize=(10,7),layout='constrained')
a=atomic['figure7_experimental_points'];ax[0,0].errorbar([x['temperature_uK'] for x in a],[x['power_kB_nK_per_ms'] for x in a],yerr=[x['power_error'] for x in a],fmt='o-',capsize=4);ax[0,0].set(title='A. Published atomic-engine points',xlabel='Reservoir kinetic temperature (µK)',ylabel='Power / kB (nK/ms)')
case=next(x for x in r if x['eye']=='ladder' and 'Burgardt' in x['source']);tr=case['result']['value']['trajectory'];t=[x['time'] for x in tr];P=np.array([x['populations'] for x in tr]);ax[0,1].stackplot(t,P.T,labels=[str(i) for i in range(-3,4)],alpha=.9);ax[0,1].set(title='B. Published model rates: population cascade',xlabel='Time (s)',ylabel='Population',ylim=(0,1));ax[0,1].legend(ncol=4,fontsize=7,title='m',loc='lower right')
ax[1,0].bar(['Three cycles','Repetitions'],[x['complete_acquisition_cells'] for x in raw],label='Acquired settings');ax[1,0].bar(['Three cycles','Repetitions'],[x['empty_acquisition_cells'] for x in raw],bottom=[x['complete_acquisition_cells'] for x in raw],label='Padded settings');ax[1,0].set(title='C. Raw array structure',ylabel='Coordinate cells');ax[1,0].legend(fontsize=8)
d=[max(abs(np.array(x['notebook_replay_populations'])-x['matched_inverse_populations'])) for x in pop];ax[1,1].hist(d,bins=25,color='#9853a3');ax[1,1].set(title='D. Readout reconstruction sensitivity',xlabel='Largest population-component difference',ylabel='Acquired settings')
f.savefig(p/'research/qhe_controls.png',dpi=170);plt.close(f)
body=subprocess.check_output(['pandoc',str(p/'research/QHE_Findings.md'),'-f','markdown','-t','html5'],text=True);figure=base64.b64encode((p/'research/qhe_controls.png').read_bytes()).decode();body+='<figure><img style="width:100%" src="data:image/png;base64,'+figure+'"><figcaption>Each panel labels its evidence stage. Panel D is a diagnostic comparison, not a corrected population claim.</figcaption></figure>'
data=json.dumps(eyes).replace('<','\\u003c')
html='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Compound Eye Universal 2.2</title><style>
:root{color-scheme:dark;font-family:system-ui,sans-serif;background:#0a111d;color:#dce6f3}*{box-sizing:border-box}body{margin:0}header,main{max-width:1180px;margin:auto;padding:28px}header{padding-top:55px}h1{font-size:clamp(32px,6vw,58px);line-height:1.04;max-width:820px;letter-spacing:-2px;margin:15px 0}h2{font-size:25px;margin-top:28px}p{line-height:1.65;max-width:920px}.eyebrow{color:#66d8cf;letter-spacing:3px;font-size:12px}.subtitle{color:#a9bcd4;font-size:19px}.stats{display:flex;gap:12px;flex-wrap:wrap;margin:28px 0}.stat,.panel,.card{background:#101f31;border:1px solid #263b53;border-radius:14px;padding:20px}.stat b{font-size:30px;display:block;color:#f6c96b}.stat{min-width:160px}nav{display:flex;gap:9px;flex-wrap:wrap}button,input,select{background:#142940;border:1px solid #35516f;border-radius:8px;padding:12px;color:#e7f0fa;font:inherit}button{cursor:pointer}button.active{background:#26616a;border-color:#5ed8c5}button:hover{border-color:#7bcde7}section[hidden]{display:none}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:14px}.card h3{font-size:17px;margin:8px 0;overflow-wrap:anywhere}.card p{font-size:13px;color:#b3c5d8}.tag{font-size:11px;color:#6ce0d1;text-transform:uppercase}.muted{color:#99adc4}.toolbar{display:flex;gap:12px;margin:20px 0;flex-wrap:wrap}.toolbar input{flex:1;min-width:240px}.contract{white-space:pre-wrap;overflow-wrap:anywhere;font-size:11px;max-height:350px;overflow:auto}.lab{display:grid;grid-template-columns:280px 1fr;gap:20px}label{display:block;margin:16px 0}input[type=range]{display:block;width:100%;padding:8px 0}.lab>*{min-width:0}pre{white-space:pre-wrap;overflow-wrap:anywhere}canvas{width:100%;height:340px;max-width:100%}.pill{color:#f6c96b;font-weight:600}table{border-collapse:collapse;display:block;overflow:auto;font-size:14px}td,th{text-align:left;vertical-align:top;padding:12px;border-bottom:1px solid #2b415a;min-width:150px}a{color:#79d6ef}code{color:#edc77c;overflow-wrap:anywhere}#research{max-width:1050px}#research h1{font-size:35px}#research p,#research li{line-height:1.75}figcaption{color:#a8bace;font-size:13px}.note{border-left:3px solid #f6c96b;padding-left:18px}footer{margin:45px 0;color:#8ba0b9;font-size:13px}@media(max-width:700px){.lab{grid-template-columns:1fr}main,header{padding:20px}.stat{min-width:130px}h1{letter-spacing:-1px}}</style>
<header><div class="eyebrow">JEROMIE N. BEASLEY · RESEARCH INSTRUMENT</div><h1>Compound Eye<br>Universal 2.2</h1><p class="subtitle">Follow channels, energy, geometry and memory as they change.</p><p>The full Python instrument and source data travel in the companion ZIP. This standalone page contains the catalog, research findings and a live illustrative heat-engine model.</p><div class="stats"><div class="stat"><b>172</b>eye versions</div><div class="stat"><b>5</b>new UPG views</div><div class="stat"><b>611</b>focused evaluations</div><div class="stat"><b>539</b>raw acquired settings</div></div><nav><button class="active" data-tab="catalog">Explore the eyes</button><button data-tab="integration">UPG & cascade</button><button data-tab="lab">Watch an Otto cycle</button><button data-tab="research">Data & findings</button><button data-tab="handoff">Use in another chat</button></nav></header><main>
<section id="catalog"><h2>Choose the view your question needs</h2><p class="muted">A registered view is not automatically executable. Expand an eye to inspect its exact contract and limitations. Existing versions are preserved.</p><div class="toolbar"><input id="query" aria-label="Search eyes" placeholder="Search memory, knot, heat, pairing…"><select id="family" aria-label="Family"><option value="">All families</option></select><select id="status" aria-label="Status"><option value="">All statuses</option><option>implemented</option><option>specified</option><option>archived_result</option></select></div><p id="count"></p><div id="cards" class="grid"></div></section>
<section id="lab" hidden><h2>When does a cascade become an engine?</h2><p>This two-level Otto illustration separates changes of level spacing (work) from changes of population (heat). It assumes complete thermalization and no cost for the controls. It is a model, not a fit to either experiment.</p><div class="lab"><div class="panel"><label>Cold gap = 1; hot gap <span id="gapv"></span><input id="gap" type="range" min="1.1" max="4" step=".1" value="2"></label><label>Hot temperature <span id="tempv"></span><input id="temp" type="range" min=".5" max="5" step=".1" value="3"></label><p>Cold temperature = 0.5.<br>Units: kB = 1.</p><label>Cycle stage<input id="stage" type="range" min="0" max="400" value="0"></label><button id="play">Play cycle</button><button id="reset">Reset</button></div><div class="panel"><div class="pill" id="stageName"></div><canvas id="cycle" width="760" height="340"></canvas><p id="ledger"></p><p class="muted">Closing the cycle matters. A fixed-gap decay sends energy into the environment but supplies no work through this Hamiltonian-control channel.</p></div></div></section>
<section id="integration" hidden>__INTEGRATION__</section><section id="research" hidden>__REPORT__</section>
<section id="handoff" hidden><h2>One complete instrument to share</h2><p>Upload <strong>Compound_Eye_Universal_2_2_Complete.zip</strong> into another chat. The ZIP includes the source deposits, all current eye definitions, implementations, prior tools and full peeling project. Opening this HTML alone does not execute Python.</p><div class="panel"><p id="prompt">Extract the Compound Eye package. Read START_HERE.md, CHAT_HANDOFF.md and research/QHE_Findings.md. Run run_all.py if execution is available. Preserve existing eyes, select relevant methods, and report the tests you actually run. Distinguish measurements, calibration, models and interpretation. Use it on the problem I give next.</p><button id="copy">Copy handoff</button></div><h3>Run the focused suites</h3><pre><code>python -m pip install -r requirements.txt\npython run_all.py</code></pre><h3>Repeat the raw-data audit</h3><pre><code>python -m pip install -r requirements-data.txt\npython audit_sources.py\npython run_all.py</code></pre><p>For Windows S-mode users, the HTML opens in a browser. Python execution can be done by a code-enabled receiving chat. No manual source edits or GitHub checkout are required.</p><p class="note">The new views support a testable quantum heat-engine direction. They do not establish a universal elemental law. The README explains how to add new versions without erasing old work.</p></section><footer>Research cutoff: 7 September 2026 · Measurements → calibrated operators → declared observables → tested interpretations.</footer></main>
<script>const eyes=__EYES__;const $=id=>document.getElementById(id);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
for(const f of [...new Set(eyes.map(e=>e.family))].sort()){let o=document.createElement('option');o.value=f;o.textContent=f;$('family').appendChild(o)}
function filter(){let q=$('query').value.toLowerCase(),f=$('family').value,s=$('status').value;let list=eyes.filter(e=>(!f||e.family===f)&&(!s||e.status===s)&&JSON.stringify(e).toLowerCase().includes(q));$('count').textContent=`${list.length} of ${eyes.length} eye versions`; $('cards').innerHTML=list.map(e=>`<article class="card"><div class="tag">${esc(e.status)} · ${esc(e.family)}</div><h3>${esc(e.title)}</h3><code>${esc(e.id)}@${esc(e.version)}</code><p>${esc(e.output_meaning)}</p><details><summary>Contract and limits</summary><pre class="contract">${esc(JSON.stringify(e,null,2))}</pre></details></article>`).join('')}
['query','family','status'].forEach(x=>$(x).addEventListener('input',filter));filter();document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('main>section').forEach(s=>s.hidden=s.id!==b.dataset.tab);document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));draw()});
function calculate(g,T){let pc=1/(1+Math.exp(1/.5)),ph=1/(1+Math.exp(g/T)),w=(g-1)*(ph-pc),qh=g*(ph-pc);return {pc,ph,w,qh,eta:w>0?w/qh:null}}
function draw(){let g=+$('gap').value,T=+$('temp').value,k=+$('stage').value/100;let a=calculate(g,T),paths=[[1,a.pc],[g,a.pc],[g,a.ph],[1,a.ph],[1,a.pc]],s=Math.min(3,Math.floor(k)),u=k===4?1:k-s,A=paths[s],B=paths[s+1],point=[A[0]+u*(B[0]-A[0]),A[1]+u*(B[1]-A[1])];$('gapv').textContent=g.toFixed(1);$('tempv').textContent=T.toFixed(1);$('stageName').textContent=['Compression · work on system','Heating · heat into system','Expansion · work out of system','Cooling · heat to bath'][s];let c=$('cycle'),x=c.getContext('2d'),W=c.width,H=c.height;x.clearRect(0,0,W,H);let X=v=>65+(v-1)/3*(W-110),Y=v=>H-50-v/.6*(H-90);x.strokeStyle='#42607e';x.lineWidth=1;x.beginPath();x.moveTo(65,30);x.lineTo(65,H-50);x.lineTo(W-40,H-50);x.stroke();x.fillStyle='#b5c8dd';x.font='14px system-ui';x.fillText('Excited population',15,20);x.fillText('Level spacing',W/2,H-12);for(let i=0;i<4;i++){x.strokeStyle=['#edc775','#ed766d','#69d7c4','#7cbaff'][i];x.lineWidth=3;x.beginPath();x.moveTo(X(paths[i][0]),Y(paths[i][1]));x.lineTo(X(paths[i+1][0]),Y(paths[i+1][1]));x.stroke()}x.fillStyle='#fff';x.beginPath();x.arc(X(point[0]),Y(point[1]),7,0,7);x.fill();$('ledger').textContent=`Work output per cycle: ${a.w.toFixed(4)}. Heat into hot stroke: ${a.qh.toFixed(4)}. ${a.eta===null?'This setting is not in the positive-work engine regime.':'Ideal efficiency: '+(100*a.eta).toFixed(1)+'%.'} Cycle closes at the final stage.`}
let timer=null;$('play').onclick=()=>{if(timer){clearInterval(timer);timer=null;$('play').textContent='Play cycle'}else{timer=setInterval(()=>{$('stage').value=(+$('stage').value+2)%401;draw()},40);$('play').textContent='Pause'}};$('reset').onclick=()=>{$('stage').value=0;draw()};['gap','temp','stage'].forEach(id=>$(id).oninput=draw);draw();$('copy').onclick=async()=>{try{await navigator.clipboard.writeText($('prompt').textContent);$('copy').textContent='Copied'}catch(e){$('copy').textContent='Select and copy the paragraph above'}};
</script></html>'''.replace('__REPORT__',body).replace('__EYES__',data)
integration=subprocess.check_output(['pandoc',str(p/'projects/upg_integration/UPG_Cascade_Integration.md'),'-f','markdown','-t','html5','--mathml'],text=True)
integration=integration.replace('src="integration_controls.png"','src="data:image/png;base64,'+base64.b64encode((p/'projects/upg_integration/integration_controls.png').read_bytes()).decode()+'"')
html=html.replace('__INTEGRATION__',integration)
import html as html_module
viewer=(p/'projects/diophantine/Diophantine_Evolution.html').read_text()
html=html.replace('<button data-tab="handoff">','<button data-tab="diophantine">Diophantine evolution</button><button data-tab="handoff">')
html=html.replace('<section id="handoff"', '<section id="diophantine" hidden><iframe title="Recorded Diophantine evolution and integrality" sandbox="allow-scripts allow-popups" style="width:100%;height:1770px;border:0" srcdoc="'+html_module.escape(viewer,quote=True)+'"></iframe></section><section id="handoff"')

(p/'START_HERE.html').write_text(html);(p/'release_counts.json').write_text(json.dumps({'eye_versions':len(eyes),'statuses':status,'sets':len(reg.sets)},indent=2));print(status)
