const add=(a,b)=>[a[0]+b[0],a[1]+b[1]],mul=(a,b)=>[a[0]*b[0]-a[1]*b[1],a[0]*b[1]+a[1]*b[0]],scale=(a,b)=>[a[0]*b,a[1]*b],div=(a,b)=>scale(mul(a,[b[0],-b[1]]),1/(b[0]**2+b[1]**2)),abs2=a=>a[0]**2+a[1]**2;
function root(a){let r=Math.hypot(...a);return [Math.sqrt(Math.max(0,(r+a[0])/2)),Math.sqrt(Math.max(0,(r-a[0])/2))]}
function optical(el,lambda,interband=1,damping=1){let q=DATA.parameters[el],E=1239.8419843320026/lambda,wp=q.plasma_eV;let e=add([1,0],div([-q.drude_strength*wp*wp,0],[E*E,E*q.drude_gamma_eV*damping]));for(let o of q.oscillators)e=add(e,div([interband*o.strength*wp*wp,0],[o.energy_eV**2-E*E,-E*o.gamma_eV]));return root(e)}
function film(n,lambda,d,ns){let r01=div(add([1,0],scale(n,-1)),add([1,0],n)),r12=div(add(n,[-ns,0]),add(n,[ns,0]));let a=2*Math.PI*d/lambda,p=scale([Math.cos(a*n[0]),Math.sin(a*n[0])],Math.exp(-a*n[1]));let den=add([1,0],mul(mul(r01,r12),mul(p,p)));let r=div(add(r01,mul(r12,mul(p,p))),den),t=div(mul(mul(div([2,0],add([1,0],n)),div(scale(n,2),add(n,[ns,0]))),p),den);let R=abs2(r),T=ns*abs2(t);return {R,T,A:1-R-T,phase:Math.atan2(r[1],r[0])}}
function spectrum(el,d,ns,dataset='measured',interband=1,damping=1){return DATA.wavelength_nm.map((w,i)=>{let n=dataset==='measured'&&DATA.measured_nk[el]?DATA.measured_nk[el][i]:optical(el,w,interband,damping);return film(n,w,d,ns)})}
function color(R){let xyz=[0,0,0],norm=0;for(let i=0;i<R.length;i++){let wt=i===0||i===R.length-1?.5:1;norm+=wt*DATA.illuminant[i]*DATA.cmf[i][1];for(let j=0;j<3;j++)xyz[j]+=wt*R[i]*DATA.illuminant[i]*DATA.cmf[i][j]}xyz=xyz.map(x=>x/norm);let m=[[3.2406,-1.5372,-.4986],[-.9689,1.8758,.0415],[.0557,-.204,1.057]],lin=m.map(a=>a.reduce((s,v,i)=>s+v*xyz[i],0)),rgb=lin.map(x=>{x=Math.max(0,Math.min(1,x));return x<=.0031308?12.92*x:1.055*x**(1/2.4)-.055});return {XYZ:xyz,hex:'#'+rgb.map(x=>Math.round(x*255).toString(16).padStart(2,'0')).join('')}}
function graph(id,x,curves,ylim,xlabel,ylabel){const c=document.getElementById(id),g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);let W=c.width,H=c.height,L=58,R=20,T=24,B=46,min=x[0],max=x.at(-1);g.fillStyle='#bac9d9';g.font='13px system-ui';g.strokeStyle='#304052';for(let j=0;j<5;j++){let yy=T+(H-T-B)*j/4;g.beginPath();g.moveTo(L,yy);g.lineTo(W-R,yy);g.stroke();g.fillText((ylim*(1-j/4)).toFixed(ylim>10?0:2),8,yy+4)}for(let j=0;j<5;j++){let xx=L+(W-L-R)*j/4;g.fillText((min+(max-min)*j/4).toFixed(0),xx-10,H-25)}g.fillText(xlabel,W/2-45,H-5);g.fillText(ylabel,L,15);curves.forEach((s,k)=>{g.strokeStyle=s.color;g.lineWidth=2.5;g.beginPath();s.y.forEach((v,i)=>{let xx=L+(x[i]-min)/(max-min)*(W-L-R),yy=T+(1-v/ylim)*(H-T-B);i?g.lineTo(xx,yy):g.moveTo(xx,yy)});g.stroke();g.fillStyle=s.color;g.fillText(s.name,L+130*k,T+17)})}
function render(){const d=+document.getElementById('depth').value,ns=+document.getElementById('outside').value,src=document.getElementById('source').value,ib=+document.getElementById('ib').value,dm=+document.getElementById('damping').value;document.getElementById('depthValue').textContent=d.toFixed(1)+' nm';document.getElementById('outsideValue').textContent=ns.toFixed(2);document.getElementById('ibValue').textContent=ib.toFixed(2);document.getElementById('dampingValue').textContent=dm.toFixed(2);document.getElementById('fitcontrols').hidden=src!=='fit';let curves=[];let colors={Au:'#efc15c',Ag:'#d8e5ec',Cu:'#e99569',Pt:'#aeb2ba'};document.getElementById('cards').innerHTML='';for(let el of ['Au','Ag','Cu','Pt']){let s=spectrum(el,d,ns,src,ib,dm),co=color(s.map(v=>v.R)),mid=s[85];curves.push({name:el,color:colors[el],y:s.map(v=>v.R)});let div=document.createElement('div');div.className='metal';div.innerHTML='<b>'+el+'</b><div class="swatch" style="background:'+co.hex+'"></div><small>'+((src==='measured'&&el!=='Pt')?'Johnson–Christy measurements':'Rakić optical fit')+'</small><p>At 550 nm<br>R '+mid.R.toFixed(3)+' · T '+mid.T.toFixed(3)+' · A '+mid.A.toFixed(3)+'</p><small>Reflected D65: '+co.hex+'</small>';document.getElementById('cards').appendChild(div)}graph('optics',DATA.wavelength_nm,curves,1,'Wavelength / nm','Reflectance');const th=+document.getElementById('angle').value*Math.PI/180,dip=Math.sin(th)**2,G=.16*dip/1.04**2;document.getElementById('angleValue').textContent=(th*180/Math.PI).toFixed(1)+'°';document.getElementById('joint').textContent='Levels: −1, +1 eV | Gap: 2 eV | Optical strength: '+dip.toFixed(4)+' | G/G₀: '+G.toFixed(4)+' | Projector metric: 0.25';graph('ions',Array.from({length:12},(_,i)=>i+1),['Au','Ag','Cu','Pt'].map(el=>({name:el,color:colors[el],y:DATA.ions[el].energies_eV})),400,'Electron removal number','Ionization energy / eV')}
if(typeof document!=='undefined'){for(let id of ['depth','outside','source','ib','damping','angle'])document.getElementById(id).addEventListener('input',render);let timer=null;document.getElementById('play').onclick=()=>{if(timer){clearInterval(timer);timer=null;document.getElementById('play').textContent='Animate thinning';return}document.getElementById('play').textContent='Pause';timer=setInterval(()=>{let x=document.getElementById('depth');x.value=+x.value<=10?200:+x.value-1;render()},80)};render()}
if(typeof module!=='undefined')module.exports={optical,film,spectrum,color};
